import { Inter } from "next/font/google";

import type { Metadata } from "next";

import "../globals.css";
import { CustomProvider } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <CustomProvider.UI>{children}</CustomProvider.UI>
      </body>
    </html>
  );
}
